"""add favorites table

Revision ID: 229e8ea76351
Revises: 6a9dc68fafab
Create Date: 2023-12-13 20:07:59.372110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229e8ea76351'
down_revision = '6a9dc68fafab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nordic_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nordic_center_id'], ['nordic_centers.id'], name=op.f('fk_favorites_nordic_center_id_nordic_centers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
