"""add Trips table

Revision ID: 6a9dc68fafab
Revises: c27dd6fcefac
Create Date: 2023-12-13 10:16:46.549176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9dc68fafab'
down_revision = 'c27dd6fcefac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nordic_center_id', sa.Integer(), nullable=True),
    sa.Column('snow_cover', sa.Integer(), nullable=False),
    sa.Column('grooming', sa.Integer(), nullable=False),
    sa.Column('weather', sa.Integer(), nullable=False),
    sa.Column('fun_factor', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['nordic_center_id'], ['nordic_centers.id'], name=op.f('fk_trips_nordic_center_id_nordic_centers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
